### ISSUE TITLE
Revert transaction if redeeming address balance is zero

### ISSUE THREAD

**Issue by TCGV** [DeFiOptions/DeFiOptions-core#7]
Steps to repro:
1. Click redeem option button upon expiration
2. Redeem once the modal pops out
3. Confirm transaction in metamask
4. Transaction get’s approved (confirmation message)
5. Repeat the cycle (modal stays open)

Expected:
Error message

Actual:
Confirmation message

Additional info:
My balance was not changed the second time, so it seems to be just a frontend error message problem

Reported by: Mr. Rock#5540

**Comment by remote-gildor** [comment]
Ok, so basically programmatically closing the modal after confirmation (or even after the submit?) should do the trick.

**Comment by TCGV** [comment]
> Ok, so basically programmatically closing the modal after confirmation (or even after the submit?) should do the trick.

Actually I was thinking of reverting the transaction in the backend, but yeah, you could also disable/close the modal while the transaction is pending to improve the UX, sort of what SushiSwap does :)

**Comment by TCGV** [comment]
![image](https://user-images.githubusercontent.com/2445889/125485724-9185d5ff-c5b2-40a1-af19-32074f198279.png)

**Comment by remote-gildor** [comment]
done 👍

**Comment by TCGV** [comment]
Closing this issue since it was dealt with in the frontend app
